### ISSUE TITLE
Have to disable DPTF, but still wants fan to turn on when required

### ISSUE THREAD

**Issue by leledumbo** [stockmind/gpd-pocket-ubuntu-respin#111]
I know Hans has submitted proper GPD fan driver, but this works only when DPTF is enabled. Due to my environment condition (man, ambient temperature here is 32.6°C right now), I need to have DPTF disabled. Without it, even with the highest allowed temperature settings, my pocket will freeze when I play game such as SuperTuxKart. So, I need the good old gpdfan daemon instead. I've blacklisted and unloaded the gpd_pocket_fan module, but still I can't start gpdfand service (same "Operation not permitted" error when gpd_pocket_fan module loaded). I'm using kernel 4.16.0-rc3.

**Comment by stockmind** [comment]
This seems to be an issue on kernel 4.16 (4.15 shouldn't be affected), have you already tried a locked BIOS or DPTF enabled with an Ubuntu version 17.10+? Freezes still happen?

**Comment by leledumbo** [comment]
> have you already tried a locked BIOS with an Ubuntu version 17.10+? Freezes still happen?

That one is actually for sure, no need to retry, but I did retry and it even freezes on simple tasks like web browsing.

**Comment by leledumbo** [comment]
As a temporary solution, I set the temp_limits options to 50000,55000,60000 (default is 5 degrees higher) in /etc/modprobe.d/whatever.conf. At least this will kick the fan earlier and indeed high performance can be maintained (geekbench4 test shows it never reaches 80°C, only 7X°C at most, and the whole test passes without freeze). When DPTF is disabled and temp reaches over 80°C, the SoC does automatic throttling somehow (despite throttling is disabled or not in BIOS) and the performance degrades. The downside? The fan is always on causing a little disturbing noise.

**Comment by ViktorWalter** [comment]
Hey, with the help of @efluffy I found the solution: The original gpdfand doesn't work with the new kernel, because the kenrel maps the control pins to different gpio numbers - 341 and 342 as opposed to 397 and 398. Change these numbers in gpdfand.py (two occurences each) and the service will work again (see https://github.com/efluffy/gpdfand/issues/7). It is based on a CPU core temperature, so DPTF can be disabled and you will still have a working fan. Sidenote: to avoid the freezing, you don't have to disable DPTF altogether, just the processor participant, which unfortunately provides the temperature used by the @jwrdegoede module.

**Comment by leledumbo** [comment]
> The original gpdfand doesn't work with the new kernel, because the kenrel maps the control pins to different gpio numbers - 341 and 342 as opposed to 397 and 398. Change these numbers in gpdfand.py (two occurences each) and the service will work again

Good catch. Now I don't have to enjoy the warmth of passively cooled pocket.

**Comment by stockmind** [comment]
@ViktorWalter Great job! 😃 Will try to test and update README troubleshooting as soon as possible
