### ISSUE TITLE
Respining the 18.04 iso,the isorespin.sh returns argument error

### ISSUE THREAD

**Issue by AlchMeow** [stockmind/gpd-pocket-ubuntu-respin#121]
Hi,
I try to respin the Ubuntu 18.04 iso, and use ./build.sh ubuntu-18.04-desktop-amd64.iso gnome bionicbeaver.

`Setting gnome monitors...
Setting Bionic Beaver environment...
Display setting: Gnome
Looking for kernel image...
Extracting latest kernel files...
Archive:  gpdpocket-20180306-4.16.0-rc3-kernel-files.zip
  inflating: linux-headers-4.16.0-rc3-stockmind-gpdpocket_4.16.0-rc3-stockmind-gpdpocket-1_amd64.deb  
  inflating: linux-image-4.16.0-rc3-stockmind-gpdpocket_4.16.0-rc3-stockmind-gpdpocket-1_amd64.deb  
  inflating: linux-libc-dev_4.16.0-rc3-stockmind-gpdpocket-1_amd64.deb  
./isorespin.sh: An argument must be specified when using '-g' or '--grub'.
`

Anybody others have this problem?

**Comment by xzavrel** [comment]
Just delete -g  "" in build.sh file on line 145. I don't know the reason why it is there as the real grub parameters are on the next line.

**Comment by stockmind** [comment]
@xzavrel Previous isorespin script versions required to clear the grub options before put the new ones:)
This behaviour seems changed in latest releases, i will update everything asap!

**Comment by linuxium** [comment]
The 'isorespin.sh' error when using the '-g ""' option was a newly introduced bug which I've now fixed in version 8.2.2. Also you have never needed to 'clear the grub options before put the new ones'. When testing new kernel builds it is often useful to see the boot sequence and removing the splash screen is advisable with custom kernels when warnings and errors may be otherwise missed.

**Comment by stockmind** [comment]
Thanks Ian for clarification!:) Sorry for the mistake, it passed too much time from the last time i had to touch those lines 😅
