### ISSUE TITLE
Optimize boot/shutdown UX

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#16]
Currently, booting is verbose, which doesn't look great due to the screen first being rotated. It would be better to suppress the verbose output during boot.

Also, it would be great if the splash image was rotated correctly during both boot at shutdown.

**Comment by stockmind** [comment]
Plymouth need to be rotated somehow, didn't succeed in doing it.

Also Grub doesn't support rotation and there is no fix for this until they decide to support it.
A patch like that perhalps has some drawback due to image buffer and other things that need to be considered so it's likely it will never be implemented or will take a lot of discussion/devices that need this.

**Comment by maxengel** [comment]
Hrm. Too bad about Grub. Doesn't seem like there is much to be done. Is it possible to not have it verbose with outputting info, and to hide the cursor, etc., until the rotation can occur during boot?

**Comment by maxengel** [comment]
Maybe this would help with the console part? https://www.kernel.org/doc/Documentation/fb/fbcon.txt

**Comment by stockmind** [comment]
FBcon is already integrated into Hans kernel. This let boot output to be rotated correclty on boot.

**Comment by maxengel** [comment]
Got it. So this is another Plymouth/elementary OS-related issue?

**Comment by stockmind** [comment]
After first update.sh run, GRUB should be ok with all the rotation things we can do at the moment.
Output text should be correctly oriented while system boots up.
The only solution  i can think of to hide output loading text is replace Plymouth with a custom splash already rotated like GPD done with windows loading splashscreen. 
I don't have experience in that and don't really care at the moment, if you will you can try to do one!
It could be just as GPD windows splash screen with just the GPD logo at center. Should be something generic because we can't know which distro is booting.

**Comment by maxengel** [comment]
Output text (which seems like verbose logging) is not rotated...

Should I create an issue prefixed with "Feature Request" for the custom splash?

**Comment by stockmind** [comment]
Run this

    sudo sed -i "s/GRUB_CMDLINE_LINUX=\"i915.fastboot=1 i915.semaphores=1\"/GRUB_CMDLINE_LINUX=\"i915.fastboot=1 i915.semaphores=1 fbcon=rotate:1\"/" /etc/default/grub
sudo update-grub

Post content of /etc/default/grub 

You are on new BIOS so quirks that match GPD Pocket may not work out of the box.

**Comment by maxengel** [comment]
1) When updating GRUB, I get the following error:
```
Warning: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
```
2) My file looks like this:
```
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT=""
GRUB_CMDLINE_LINUX="i915.fastboot=1 i915.semaphores=1 fbcon=rotate:1"

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
```

**Comment by maxengel** [comment]
The logging is still verbose, but rotated correctly :-)

**Comment by stockmind** [comment]
Good to know, fix the grub config issue about time, choose as it says what timeout use.
I close this and if you have time and can create the feature request it would be great, thanks!

**Comment by maxengel** [comment]
Sorry, are you saying you fixed it, or that I need to?

typed on a touchscreen...
