### ISSUE TITLE
SQUASHFS error: unable to read

### ISSUE THREAD

**Issue by spilipenko** [stockmind/gpd-pocket-ubuntu-respin#31]
There were multiple "SQUASHFS error: unable to read" during boot of gpdpocket-20170725-ubuntu-17.04-desktop-amd64.iso
After fifth attempt it suddenly booted OK. The USB stick is fine, I tried two sticks, each of them was booting standard Ubuntu without a problem.

**Comment by stockmind** [comment]
First report like this about those ISOs.
Other users have burned and booted them fine. Some squashfs error may
happen but shouldn't fail to boot.

Check md5sum

$ md5sum gpdpocket-20170725-ubuntu-17.04-desktop-amd64.iso
9e30f0a26c8e0fe73082a2500e6c8331
gpdpocket-20170725-ubuntu-17.04-desktop-amd64.iso


Hash posted by ju2wheels.
I will provide some hashes when i have access to my usual setup or a better
connection.

Also what program are you using to write iso on USB?


Il 01 ago 2017 06:31, "spilipenko" <notifications@github.com> ha scritto:

I was trying to use two respun .iso-s:
gpdpocket-20170725-ubuntu-17.04-desktop-amd64.iso
and gpdpocket-20170724-ubuntu-17.04-desktop-amd64.iso
Both resulted in multiple "SQUASHFS error: unable to read" during boot. I
tried two different usb sticks. Booting standard ubuntu iso works fine with
both sticks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/31>, or mute
the thread

**Comment by spilipenko** [comment]
Thanks for the md5, it was correct.

The problem is with the USB-C port: when I plug a USB with this .iso to a normal size USB port, it works. If I use USB-C with an adapter it crashes. Standard Ubuntu-16.04 was booting from both ports.
________________________________

**Comment by sduensin** [comment]
Thanks for the follow up about the adapter.  I had the same problem with the adapter that came with my Pocket.  Booting from the "old" USB 3 port worked fine.

**Comment by kanocz** [comment]
@sduensin for now is no support for USB-C data in linux on GDP Pocket, so it's impossible to boot from USB-C adapter or flash
