### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by cawilliamson** [stockmind/gpd-pocket-ubuntu-respin#38]
Hey,

I'm wondering if you're up for a collaboration on getting Linux working well on the GPD Pocket?

I think a combination of a fixed installer and an ansible-based updater for this stuff would be awesome and would save us a lot of time trying to keep up with each others work! 👍 

My thought are:

1.) Install with isorespin.sh'd ISO - I would need to do something about Arch here but arch folks tend to be a tech savvy bunch anyway - a well written Wiki article would likely get them off to a great start - could even submit an AUR package.

2.) In the respun ISO we add the ansible-update script (basically it would install git, ansible, yada yada and get the system updated with the latest code from our combined repo.)

Any thoughts? If you don't like the idea no sweat - just let me know either way. :)

Cheers!

Chris

**Comment by stockmind** [comment]
You know that i'm pro to this! 👍 

1) I agree with Wiki thing, and an AUR package would be awesome 💃 Maybe we can also find another way to respin iso other than isorespin.sh, i was looking into it these days.
2) We can do it during respin. Let me know how you want proceed :)

**Comment by stockmind** [comment]
About the update thing i have already a really simply bash script that take care of everything that could be easily extended.
I was thinkin in these days to write to you about the possibility of extend it with your discoveries about Arch and other distros.

**Comment by stockmind** [comment]
A simply bash script seems easily to maintain to me than ansible but i'm open to suggestions! :)

**Comment by cawilliamson** [comment]
Great, it'll be good to collaborate on this - I've re-uploaded my ansible playbooks at https://github.com/cawilliamson/ansible-gpdpocket if that helps.

Ok - honestly - I can't stand the bash script approach! :P The problem is - let's say for example you want install wget on any distro:

`- package: name=wget`

That's it!

In bash it would be something along the lines of:

```
if [ -f /usr/bin/pacman ]; then
  pacman -Sy --noconfirm wget
elif [ -f /usr/bin/apt-get ]; then
  apt-get -y install wget
elif [ -f /usr/bin/emerge ]; then
  emerge --sync
  USE="blksha1 curl webdav" emerge net-misc/wget
else
  echo "err... we didn't code in bash stuff to handle this :("
fi
```

See what I mean? I find the ansible stuff SO much easier to work with - the learning curve isn't too bad to be honest - now Puppet or Chef - those are a pain to learn but ansible is lightweight, fast and easy. :)

As for replacing isorespin.sh - I was thinking about this - I'm wondering if I could perhaps find a solution to this and add support to the ansible playbooks - for example:

`bash bootstrap.sh --iso=<file path>`

Then that invokes the ansible playbook to run against that iso (I'm sure it wouldn't be too difficult to mount the ISO on loopback, modify what's needed, etc. and then build it back to an ISO again... I'll try some experiments with this too.

Ultimately I think it would be awesome to have:

1.) Prebuilt ISOs for major distros (a kind of "bootstrap ISO") - doesn't need super flashy cutting edge kernel, audio, yada yada. Just needs to be able to boot with working wifi, the display rotated properly and install the OS.

2.) A way to build ISOs for custom distros (like gentoo or something kinda non-mainstream - no offense Gentoo-ers - I used to be one of you! 👍 )

3.) A pre-bundled update script - my only concern with this is - we would need a way to only ensure stable kernels get pushed - building directly from the hans repo is awesome but it comes with a LOT of instability risk for obvious reasons - more thought needed here.

**Comment by kanocz** [comment]
@cawilliamson getting all drivers work just on live iso is very important for testing and deciding if you want to install this version or no... and ansible is perfect for set of servers, but on individual workstation this will much more harder for customize (everyone can easily modify update.sh, ansible requires reading of documentation and so on) 
+ everyone can install ansible without any problem on just installed system if required... so probably better just to include ansible installation script and do some agreement on file naming, so ansible will not install duplicate rules for wifi, sound and so on

**Comment by cawilliamson** [comment]
I'm actually working on a bootstrap-iso script which will work alongside the ansible stuff.

stockmind is free to use it as he chooses too since I know he's seeking an alternative to isorespin.sh which has too many limitations (debian only, seriously? 👎 )

My plan is you have two options:

- bootstrap-system.sh
- bootstrap-iso.sh

That should then mean we can merge all of this crazy stuff in to one big repo, preinstall all the junk necessary for ansible and updates. Ultimately the end user is unlikely to care if we're using ansible, bash or a collection of string and tape. They really just want a working system with the minimum amount of fuss and I think merging this all in to one project is the best way forward for this since, as you mention, there are SO many naming differences, approach differences, etc. and they all achieve EXACTLY the same result.

I'm hoping to get this rolled out today/tomorrow once I've finished building and testing the script but it's really not that complex. Not sure why isorespin.sh is SO long and cumbersome - seems like overkill.

**Comment by cawilliamson** [comment]
I have achieved what I set out to achieve and have created a completely new bootstrap-iso script which supports:

- Arch-based distributions (ArchLinux, Manjaro, etc.)
- Debian-based distributions (Debian, Kali, Mint, Ubuntu, etc.)
- Gentoo-based distributions (Funtoo, Gentoo, etc.)

Fedora support coming soon.

More info at:
https://www.reddit.com/r/GPDPocket/comments/6rszbo/project_linux_installer_for_gpd_pocket/

What I'm thinking is we could both work on my repo at this point and cherry pick the best from your respin work. I'm not planning to drop ansible at this point - the rag tag collection of bash scripts just doesn't seem like a good solution to me. More folks will understand them but the quality of the final setup is lower - an example of this is - there seems to be 6-7 scripts to rotate the display.

I'm curious what what your thoughts are on this @stockmind ?

**Comment by stockmind** [comment]
I don't really like your attitude, but your work is awesome and laudable.
As i already said to you in private when you closed the first time your project, i wanted to have both projects alive to let users have a choice and different approaches, pulling my discoveries on your ansible scripts as i've done, and didn't want a "competition" feel.
The ansible approach is just a bit unusual for typical user but the learning curve is not that bad.
I can stand that and will redirect users to your repo from mine from README.
You dedicated so much time on this and it deserve a good documentation, so i can suggest to copy some sections of my README and also take the instruction of the reddit post on that. 
It's better to have everything in one place instead of multiple domains.
I will not have lot of free time to work on this month and probably for the next few months due to work/study duties.
This said, i will not shutdown this repo and will update it whenever i find a better way to handle things, as i don't really agree to hiding things as it may be helpful for someone.
I agree to find a naming convention and because you seems to have more time than me to work on this i will align names to yours so they will not conflict. This is a thing that i will care, so it isn't something you have to worry about.
I will contribute to your repository exactly as i will contribute to mine as i've already proposed to you the first time you closed with GPD work.
I think that it's better to let user choose the environment they like most.
As i said i will debug and contribute to your scripts as i've already done, so you shouln't worry about anything.

**Comment by cawilliamson** [comment]
I don't want to fall out about this but I do want to make a few points:

- There has been a lot of work taken by you directly from my repo without any credit given. This is your choice but it does demonstrate a lack of respect and a poor attitude.

- This point about Ansible is simply nonsense - what we're deploying here is system configuration. Ansible is a configuration manager. A collection of hacky bash scripts are always going to be problematic - why, for example, would I write a whole set of code to handle various package managers (remember, my work supports a lot more than just Ubuntu) when I could just use existing code which is vastly more tested in mission critical environments than my bash scripts would ever be?

- There is no simple way to update your existing install with your repo - it's "reinstall or nothing" from what I can see - that doesn't work. I don't want to reinstall Ubuntu once a week.

- Your repo only supports Ubuntu and a few derivatives - this doesn't work for a lot of people who want Arch, Gentoo, Debian, Kali, yada yada yada. I'm also working on Fedora support which should help some folks out. Ultimately you're held captive by isorespin.sh at the minute which I have now removed as a limitation - feel free to take my iso boostrapping code if you choose.

- Your repository is extremely custom - like defaulting to 175% zoom - what's that all about? I don't like this approach - My aim is to setup the GPD Pocket with the essential configs in place needed for it to work and then get the hell out of the way and let the end user customise it as they choose (an example of this is - fan control options are available at /etc/gpd/fan.conf which allows customisation but uses sane defaults.)

Ultimately - I don't like your approach to doing things here and you don't seem to like mine and y'know what? That's fine! That's the wonder of open source but I haven't told anyone not to use your repository nor your code. I am, however, a little frustrated that you're calling my attitude out when you took a lot of my work and gave zero credit.

I think the best way forward from my point of view is to keep the two projects completely separate as it seems like our two approaches are fundamentally different and we could both do without the drama.

**Comment by stockmind** [comment]
I've always asked your permission and always gave credits for everything as you can see on your first GPD Reddit post and as i already said to you in private. 
I started this repo just to help people move to linux on GPD when there was just a collection of tips and tricks on Reddit days before your ansible work was published or mentioned. I don't really understand all this hate.
I had feel this contrast by you but had just hoped it was an unmotivated feeling. But your lack of reply on my post or issue was a good clue.
The first thing that i wanted to be clear was the people behind most of the work and that's what i've published for first on README on first section.
You thanked for the shout out on your first post here and i hope it wasn't ironic, because is what i've done right from the start, give a shout out on who worked to make this a reality.
I'm sorry that you feel frustrated about this, and never wanted to create a situation like that.
The fact that the script on which this repo is based have limitation is the first reason that urged me to write to you about your decision of quit everything because your ansible approach was supporting so much systems and was suitable for users different from the one that my work was probably helping.
Most of the work are tips and tricks that can be gathered on GPD Win wiki, Hans blog, Intel Arch Wiki,  
other than your re-write of gpdfand daemon and rotation script. I've asked to you if i could integrate it and you answered me that everything of your work was open and free to use. 
I really don't understand this drama.
You quitted all of a sudden your work and started to be salty and not very polite on issues opened by users here.
As i've already said i will link your project on README as a better and more supported one, because it is, as you got a working universal-respinning script before me and you got better fixes for challange that i was also taking but didn't had time to complete.
You are taking this too seriously and i'm sorry.
We should support, not argue like this.

**Comment by stockmind** [comment]
Also i just want to make out some points:

    - There is already an update.sh script that works and that doesn't require reinstall.
    - You approach is to have a basic config, mine is to have a fully-working (in Live or not) system already configured as Win version is, so with a 175% scaling of UI and things like that, usable from anyone that has poor view right from the start. And scaling to me is the only "custom" thing here, other than customizing an ISO install... (i'm talking also about bluetooth on Live, and audio auto select, things that maybe your respinning script now already cover)
    - After i've pointed out my perplexity about it, and you have pointed out your more than valid reasons, I've already told you that Ansible is ok, just not that typical. And your support for so much systems is the exact reason because your approach is better as you succeed to get it working.

The only thing that i'm saying is that i will also support this and not shutting down or hiding this because i don't feel it's the right thing to do. 

I've already asked you to have a situation like this (have your project alive) and it's happening. I'm happy and as i already said, i will help.

I didn't liked some behaviour but that doesn't mean i dont respect you as a developer and as a person, I'm sorry that there have been ambiguous situations and that this mistake and this misunderstanding has arisen.

You seems really passionate about this project and this is just cheering and charming other than great because you had found things like the audio bug thing on bugzilla way before anyone else and was already trying to get it solved for everyone.

I think that we can stop this and close this argue as it's not that productive for anyone.
