### ISSUE TITLE
Freeze when watching YT

### ISSUE THREAD

**Issue by fishkopf** [stockmind/gpd-pocket-ubuntu-respin#40]
Hey 
I was using the image of Ubuntu 16.04.3 LTS, and the kernel files of chrisaw* and the most recent repository.
I have an issue, where the system freezes when i watch a Full HD video on Youtube/Twitch on the GPD under Linux.
I thought it has something to do with processor workload, but running "stress -c 4" for 5 minutes does not let the system freeze. So i thought maybe something is wrong with my pocket, but watching videos under Windows is no problem, furthermore i just tried torchlight 2 under windows to use the GPU and CPU alike, their seems to be no problem either. So i guess  there is still something wrong with the image. 

I don't really have a clue where I could get further information about the reasons for the freeze, any ideas? Has anyone experienced similar issues?

*Edit: A few more informations, I installed the new linux-sunxi kernel (4.13.0-rc3) and the problem persist. I did not build the image from scratch i just installed the kernel onto the existing system, ill try  this next.
Also i found out, that starting Android Studio and compiling the 4.13.0 kernel freezes the device as well (had to compile it on a separate laptop).

**Comment by stockmind** [comment]
Could you test if crash happens when you use things related to online content? (Android Studio connect a lot to internet to fetch packages and for compilation purpouse). 
Watching a video offline works without crash? A 1080p one or a big video.
Crashes on my system was just related to broadcom WiFi driver.

I can suggest you to try an iso builded using cawilliamson work.
It should work better and should be the supported one in future.

https://github.com/cawilliamson/ansible-gpdpocket

**Comment by stockmind** [comment]
This still occur on latest 4.13-rc5 kernel?
