### ISSUE TITLE
Total block with Ubuntu 16.04

### ISSUE THREAD

**Issue by petrmatula190** [stockmind/gpd-pocket-ubuntu-respin#43]
Anyone who tryed build Ubuntu 16.04 with kernels standard from this repo? I have installed clean and upgraded Ubuntu 16.04.2. I have total lag (can't switch to tty1-6, I must total restart with power button). I tryed stock kernel 4.12 and custom baterry kernel 4.13. Both have this issue.  I cannot switch to tty for debuging, so Is it any way for debug it?
Any idea what is wrong? I going to try Ubuntu 17.04 on evening, but i prefer LTS versions.

I had new one Pocket, because my old pocket have screen flickering after 2 days. And old Pocked had the same issue + live 17.04 had too. 16.04 have not any lag on Live.

**Comment by stockmind** [comment]
It seems that 16.04 and distro based on that get stuck after a while of
use. Still doesn't know the cause. Could be version of packages that have
issues. 17.04 doesn't seems to have this problem. I need to rest and check
dmesg and logs to try to isolate the problem.

Il 15 ago 2017 15:54, "Peter" <notifications@github.com> ha scritto:

Anyone who tryed build Ubuntu 16.04 with kernels standard from this repo? I
have installed clean and upgraded Ubuntu 16.04.2. I have total lag (can't
switch to tty1-6, I must total restart with power button). I tryed stock
kernel 4.12 and custom baterry kernel 4.13. Both have this issue. I cannot
switch to tty for debuging, so Is it any way for debug it?
Any idea what is wrong? I going to try Ubuntu 17.04 on evening, but i
prefer LTS versions.

I had new one Pocket, because my old pocket have screen flickering after 2
days. And old Pocked had the same issue + live 17.04 had too. 16.04 have
not any lag on Live.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/43>, or mute
the thread

**Comment by petrmatula190** [comment]
I will try record dmesg and /var/log. I hope it will be enough to turn off after the lag, boot live from USB and download it from the disk.

**Comment by petrmatula190** [comment]
There is some logs after total lag, I hope to resolve it. Now, I installed 17.04 from your prebuilded iso and it is works 99% fine (only hedphones sound have some quiet lags).

 [log_16.04.zip](https://github.com/stockmind/gpd-pocket-ubuntu-respin/files/1227140/log_16.04.zip)

**Comment by petrmatula190** [comment]
Anybody tryed 16.04 again? I still have 17.04 and it had some problem, around 3-4 lags/3 days, but absolutely better than 16.04 witch 1lag/1boot on everytime.

**Comment by stockmind** [comment]
Can you make a video or something about your lags? System gets stuck like a kernel panic?
No problem in windows?
Have you tried latest 4.13-rc5 kernel?

**Comment by petrmatula190** [comment]
Sorry I can't, because I have installed 17.04 and my plan is switch to cawilliamson/ansible-gpdpocket. And of course I used latest kernel, But not on 16.04, I was trying only latest 4.13rc2 which was available in this time.
